services:
  backend:
    container_name: parcial1_backend
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - parcial1_redis
  
  #Redis
  parcial1_redis:
    image: redis
    container_name: parcial1_redis
    ports:
      - 6379:6379

  #Postgres
  parcial1_db:
    image: postgres
    container_name: parcial1_postgresql
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/PostgreSQL
